#!/usr/bin/env bash
# Generate placeholder SFX with ffmpeg (synthesised sine + click tones).
# Real CC0 SFX can be sourced from opengameart.org or freesound.org
# manually — this script gives the game something to play immediately.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUT_DIR="$ROOT_DIR/assets/audio/sfx"

mkdir -p "$OUT_DIR"
cd "$OUT_DIR"

if ! command -v ffmpeg >/dev/null; then
    echo "ERROR: ffmpeg not found. Install with: sudo apt install ffmpeg" >&2
    exit 1
fi

# Helper: generate one short WAV from filter expression
gen() {
    local out="$1"; shift
    local dur="$1"; shift
    local filt="$1"
    if [[ -f "$out" ]]; then return; fi
    ffmpeg -y -f lavfi -i "${filt},atrim=duration=${dur}" \
        -ar 22050 -ac 1 -c:a pcm_s16le "$out" 2>/dev/null
    printf "  ✓ %s\n" "$out"
}

# Each SFX is a short synth tone designed to feel right:
# - sword_hit: low metallic thud (decaying sine + noise)
gen sword_hit.wav    0.15 "sine=frequency=110:duration=0.15,volume='exp(-30*t)'"
gen sword_miss.wav   0.20 "sine=frequency=220:duration=0.20,volume='exp(-15*t)'"
gen spell_cast.wav   0.40 "sine=frequency=440:duration=0.4,vibrato=f=8:d=0.5,volume=0.5"
gen spell_fire.wav   0.60 "sine=frequency=180:duration=0.6,vibrato=f=15:d=1,volume='1-t/0.6'"
gen spell_heal.wav   0.50 "sine=frequency=880:duration=0.5,volume='exp(-3*t)'"
gen monster_die.wav  0.40 "sine=frequency=80:duration=0.4,volume='exp(-5*t)'"
gen party_damage.wav 0.20 "sine=frequency=150:duration=0.2,volume='exp(-10*t)'"
gen footstep.wav     0.08 "sine=frequency=60:duration=0.08,volume='exp(-50*t)'"
gen door_open.wav    0.50 "sine=frequency=300:duration=0.5,vibrato=f=4:d=0.5,volume='1-t/0.5'"
gen menu_move.wav    0.05 "sine=frequency=1200:duration=0.05,volume='exp(-30*t)'"
gen menu_pick.wav    0.10 "sine=frequency=900:duration=0.1,volume='exp(-20*t)'"

cat > "$OUT_DIR/README.txt" <<'EOF'
Sound effects (procedurally generated with ffmpeg).

Each WAV is a short synthesised tone matched to its game event:
- sword_hit:    low decaying sine     (melee connects)
- sword_miss:   higher attack-decay   (melee misses / wall bump)
- spell_cast:   warbling sine         (any spell starts)
- spell_fire:   low vibrato           (HALITO/MAHALITO/TILTOWAIT)
- spell_heal:   high decaying chime   (DIOS/DIAL/MADI)
- monster_die:  thud                  (group goes to 0 HP)
- party_damage: short low burst       (character takes damage)
- footstep:     very short click      (maze movement)
- door_open:    descending chord      (entering a door)
- menu_move:    high tick             (↑↓ in menus)
- menu_pick:    higher confirm        (Enter / hotkey)

Replace any file with a real CC0 sound from OpenGameArt.org or
freesound.org for better quality.

Generated by tools/fetch_sfx.sh.
EOF
echo "Wrote 11 SFX files to $OUT_DIR"
